version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/satc

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
      runas: root

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: root
